// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbcuKTvfOvhQ1-2QJ8l3iV_vCBNj81AME',
    appId: '1:653681524218:web:7d6e8e1ad01ae5bdf2b843',
    messagingSenderId: '653681524218',
    projectId: 'travel-flutter-2da51',
    authDomain: 'travel-flutter-2da51.firebaseapp.com',
    storageBucket: 'travel-flutter-2da51.firebasestorage.app',
    measurementId: 'G-LSHVS67V95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD09ceWvs1u57DURTecmLzGtKTYFgiKrEw',
    appId: '1:653681524218:android:67d07d60b6188206f2b843',
    messagingSenderId: '653681524218',
    projectId: 'travel-flutter-2da51',
    storageBucket: 'travel-flutter-2da51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqAKEGKGplQIrewAcCZZCh6fFKlYHNOws',
    appId: '1:653681524218:ios:9d09438dcffcff90f2b843',
    messagingSenderId: '653681524218',
    projectId: 'travel-flutter-2da51',
    storageBucket: 'travel-flutter-2da51.firebasestorage.app',
    iosBundleId: 'com.example.travelFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqAKEGKGplQIrewAcCZZCh6fFKlYHNOws',
    appId: '1:653681524218:ios:9d09438dcffcff90f2b843',
    messagingSenderId: '653681524218',
    projectId: 'travel-flutter-2da51',
    storageBucket: 'travel-flutter-2da51.firebasestorage.app',
    iosBundleId: 'com.example.travelFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbcuKTvfOvhQ1-2QJ8l3iV_vCBNj81AME',
    appId: '1:653681524218:web:9427f66b4d01cec7f2b843',
    messagingSenderId: '653681524218',
    projectId: 'travel-flutter-2da51',
    authDomain: 'travel-flutter-2da51.firebaseapp.com',
    storageBucket: 'travel-flutter-2da51.firebasestorage.app',
    measurementId: 'G-LLLVGE639Z',
  );
}
